version: '3.5'

volumes:
  certificates:

services:
  cert:
    container_name: esc-proxy-ssl
    image: uowcpc/pithia-esc-proxy:latest
    build:
      context: cert/
      args:
        - SERVICE_URL=http://frontend.pithia.eu:8080
        - SERVICE_DOMAIN=esc.pithia.eu
        - SERVICE_EMAIL=kagiald1@westminster.ac.uk
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certificates:/etc/letsencrypt
    healthcheck:
      test: [ 'CMD', '/opt/status.sh' ]
      start_period: 30s
      interval: 1m
      timeout: 5s
    restart: unless-stopped